-- Ejecuta este script conectado como PORTFOLIO_API después de 02_seed_data.sql.

SELECT 'ICON' AS TABLE_NAME, COUNT(*) AS ROWS_COUNT FROM ICON
UNION ALL
SELECT 'SUBTYPE_DESCRIPTION', COUNT(*) FROM SUBTYPE_DESCRIPTION
UNION ALL
SELECT 'AUDIO', COUNT(*) FROM AUDIO
UNION ALL
SELECT 'IMAGE', COUNT(*) FROM IMAGE
UNION ALL
SELECT 'DEMOS', COUNT(*) FROM DEMOS
UNION ALL
SELECT 'IMAGE3D', COUNT(*) FROM IMAGE3D
UNION ALL
SELECT 'MEDIA', COUNT(*) FROM MEDIA
ORDER BY TABLE_NAME;

SELECT
  A.ID_AUDIO,
  A.TITLE_AUDIO,
  A.URL_AUDIO,
  A.TYPE_AUDIO,
  A.DESCRIPTION_AUDIO,
  S.DESCRIPTION_SUBTYPE
FROM AUDIO A
JOIN SUBTYPE_DESCRIPTION S ON S.ID_SUBTYPE = A.SUBTYPES_AUDIO
ORDER BY A.ID_AUDIO;

SELECT
  M.ID_MEDIA,
  M.TITLE_MEDIA,
  M.URL_MEDIA,
  I.TITLE_ICON AS ICON_TITLE
FROM MEDIA M
JOIN ICON I ON I.ID_ICON = M.ICON_MEDIA
ORDER BY M.ID_MEDIA;
