# Deshabilita la creaci�n autom�tica de tablas
spring.jpa.hibernate.ddl-auto=none

# Habilita la impresi�n de consultas SQL en la consola
spring.jpa.show-sql=true

# Deshabilita la apertura autom�tica de sesiones en vista
spring.jpa.open-in-view=false

# Configuraci�n de la fuente de datos
# Para conectarse a la base de datos Oracle
# jdbc:oracle:thin:@//[host]:[port]/[SID o Service Name] -- oracle 1521 port
# spring.datasource.url=jdbc:oracle:thin:@localhost:1521/xe
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:xe
spring.datasource.username=LocutorBD
#spring.datasource.password=${env.ORACLE_PASSWORD}
spring.datasource.password=923989388
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# HikariCP settings
#spring.datasource.hikari.connection-timeout=60000
spring.datasource.hikari.validation-timeout=5000
spring.datasource.hikari.maximum-pool-size=5

# logging
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE

logging.level.org.hibernate.type.descriptor.sql=trace
logging.level.=error
logging.level.oracle.jdbc=debug

# Configuraci�n del puerto del servidor
server.port=7070

spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.use_sql_comments=true
spring.devtools.livereload.enabled=false




